language: cpp
os: linux
dist: bionic
sudo: required

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake

matrix:
    include:
        - name: "Native build & test"
          before_script:
          - sudo apt-get install -y cmake  # stock cmake is too old
          - mkdir build
          - cd build
          - cmake ..
          - make
          script: make test
        - name: "Arduino build"
          before_script:
          - sudo apt-get install -y cmake  # stock cmake is too old
          - mkdir build
          - cd build
          - ../bootstrap_arduino.sh
          script: make
