language: cpp
os: linux
dist: bionic
sudo: required

addons:
    apt:
        packages:
            - build-essential

install:
    # stock cmake is too old, download a newer version
    - curl -L https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz -o cmake-3.13.4-Linux-x86_64.tar.gz 
    - tar xf cmake-3.13.4-Linux-x86_64.tar.gz
    - export PATH=${PWD}/cmake-3.13.4-Linux-x86_64/bin:${PATH}

matrix:
    include:
        - name: "Native build & test"
          before_script:
          - mkdir build
          - cd build
          - cmake ..
          - make
          script: make test
        - name: "Arduino build"
          before_script:
          - mkdir build
          - cd build
          - ../bootstrap_arduino.sh
          script: make
