
     
name: Arduino CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create build directory
      run: mkdir -p ${{github.workspace}}/build
    - name: Bootstrap Arduino
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/bootstrap_arduino.sh
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make
